server:
  port: 8080

spring:
  application:
    name: aerospike-ui-backend

aerospike:
  hosts: 10.249.218.92:3000,10.249.218.94:3000,10.249.218.93:3000
  user: appuser
  password: m}0"Uiu27`zX
  namespace: ucm_dev
  connection:
    timeout: 5000
    max-conns-per-node: 64
    max-commands-in-progress: 5
    event-loop-threads: 4
  read:
    socket-timeout: 250
    total-timeout: 250
    max-retries: 0
  write:
    socket-timeout: 250
    total-timeout: 250
    max-retries: 0
  batch:
    socket-timeout: 250
    total-timeout: 250
    max-retries: 0

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.aerospike.ui: DEBUG
    com.aerospike.client: INFO
